baseURL = "https://ting2313.github.io/tainanplayback/"
locale = 'zh-tw'
title = '南飛．嚼事一人一故事劇團'
theme = 'ananke'

[taxonomies]
  tag = "tags"
  category = "categories"
  location = "locations"

[caches]
[caches.images]
dir = ':cacheDir/images'